language: node_js
sudo: true
addons:
  apt:
    sources: ['ubuntu-toolchain-r-test']
    packages: ['libmicrohttpd-dev','libcurl4-openssl-dev','libgoogle-glog-dev','libgflags-dev','libc++-dev','wget','pkg-config']
before_install:
    - npm install -g npm
    - wget https://github.com/bazelbuild/bazel/releases/download/0.3.1/bazel_0.3.1-linux-x86_64.deb
    - sha256sum -c tools/bazel_0.3.1-linux-x86_64.deb.sha256
    - sudo dpkg -i bazel_0.3.1-linux-x86_64.deb
node_js:
    - "14"
install:
  - cd Nice2Predict/ && bazel build //...
  - cd UnuglifyJS/ && npm ci
  - npm i
before_script:
  - cd UnuglifyJS/ && ./extract_features.py --dir . > ../training_data
  - pwd
  - export BASE_PATH=$(pwd) && cd Nice2Predict/ && bazel run n2p/training/train_json -- --logtostderr -num_threads 16 --input $BASE_PATH/training_data --out_model $BASE_PATH/model/